import { Literata, Rubik } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Hero from "./components/hero/hero";
import Team from "./components/team/team";
import FooterContainer from "./components/footer/footer-container";

// If loading a variable font, you don't need to specify the font weight
const literata = Literata({
  weight: ["400", "200"], // Specify the weights you need
  subsets: ["latin"],
  variable: "--font-literata",
});

const rubik = Rubik({
  weight: ["400"], // Specify the weights you need
  subsets: ["latin"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${literata.variable} ${rubik.variable}`}>
        {/* <div className="container"> */}
          <Header />
          {children}
        {/* </div> */}
        <FooterContainer />
      </body>
    </html>
  );
}
